### ISSUE TITLE
Refactor TableIterator to instead use Iterator<CSVRecord> with Apache Commons CSV

### ISSUE THREAD

**Issue by georgeslabreche** [frictionlessdata/tableschema-java#18]
Apache Commons CSV:
https://commons.apache.org/proper/commons-csv/

Apache Commons CSV was used for datapackage-java. We should be consistent on how we implement iteration for both tablechema-java and datapackage-java.

**Comment by georgeslabreche** [comment]
@roll thoughts?

**Comment by roll** [comment]
@georgeslabreche 
In Python/JavaScript we don't touch `csv` parsing on data package level at all. It's encapsulated in `tableschema.Table` and re-used. Don't we use this approach in Java?

**Comment by georgeslabreche** [comment]
@roll a really dumb mistake from my part. For some reason I did not think of re-using what was already done in tableschema but now I clearly recall there was guidelines to do this and this was the reason why we started working on tableschema before datapackage-java! I will do the necessary refactoring which will preserve the approach using Apache Commons CSV.
