### ISSUE TITLE
Implementing error list/tracking for non strict validation.

### ISSUE THREAD

**Issue by georgeslabreche** [frictionlessdata/tableschema-java#19]
Currently, setting strict to false simply ignores errors rather than storing them in an error list.

**Comment by georgeslabreche** [comment]
@roll this should be addressed, correct?

**Comment by roll** [comment]
@georgeslabreche 
Yes. In `strict=false` mode we're collecting errors into `schema/resource/package.errors` and having `schema/resource/package.valid` flag derived from it. 

Also after some user feedback I've made non strict mode as default. The main feedback thought was that first thing people just wants to read data and often just doesn't care about descriptor validity. If they care they check `valid/errors` props.
