### ISSUE TITLE
some doubt regarding the "number" type of field

### ISSUE THREAD

**Issue by jackyq2015** [frictionlessdata/tableschema-java#21]
There are some confusion different between below 2 instances. Basically  they are the same class type but behave differently.
`
 @Test

    public void testFieldCastNumber() throws Exception{   
        Field intField = new Field("intNum", Field.FIELD_TYPE_NUMBER);
        Field floatField = new Field("floatNum", Field.FIELD_TYPE_NUMBER);
        `

For example, if I do intField.castValue("16289212000") it will fail since it is exceed the upper limit of int but if I do floatField.castValue("16289212000.0") will success. My feeling is that its behaviour is determined by the value passed in but NOT the class itself. This cause issue when try to validate a column with "number" type of have mix of number with and without trailing decimal. they both should pass the validation. But it will fail the one without the trailing decimal but exceed the upper limit of integer,  which does not sounds right. Sample data set:
https://github.com/datasets/gdp/blob/master/data/gdp.csv

**Comment by jackyq2015** [comment]
Just checked the spec, there is two field types: number an integer.
so I would assume that the number should cover all the float type with and without trailing decimal.

**Comment by iSnow** [comment]
If you are still around... 

I believe that field type `integer` in Java should be long, not int, because int is too limited. Field type `number` should probably be double. This way,  fields of type `number` would always be considered floating point, even if they don't have a decimal dot.

**Comment by iSnow** [comment]
Looked into it a bit deeper, you are spot on. 

[According to spec](http://frictionlessdata.io/specs/table-schema/index.html#number), a number field consists of "a non-empty finite-length sequence of decimal digits".

I replaced the usage of `Integer` and `Float` for integer-fields and number-fields respectively with `BigInteger` and `BigDecimal` which rids us of the size limitations.

There are now two tests that cover the both cases you mentioned above, one literal, the other from the GDP CSV file:

    @Test
    @DisplayName("Test fix for Issue https://github.com/frictionlessdata/tableschema-java/issues/21")
    void testIssue21() {
        IntegerField intField = new IntegerField("intNum");
        NumberField floatField = new NumberField("floatNum");

        BigInteger intVal = intField.castValue("16289212000");
        Number floatVal = floatField.castValue("16289212000.0");
        Assertions.assertTrue(floatVal instanceof BigDecimal);
        Assertions.assertEquals(((BigDecimal)floatVal).toBigInteger(), intVal);
    }

    @Test
    @DisplayName("Test fix for Issue https://github.com/frictionlessdata/tableschema-java/issues/21")
    void testInferSchemaFromHugeTable() throws Exception{
        File f = new File("data/gdp.csv");
        File schemaFile = new File(TestHelper.getTestDataDirectory(), "schema/gdp_schema.json");
        Schema schema = null;
        try (FileInputStream fis = new FileInputStream(schemaFile)) {
            schema = new Schema(fis, false);
        }
        Table table = new Table(f, TestHelper.getTestDataDirectory(), schema);
        Iterator iter = table.iterator(true, false, true, false);
        Object obj = null;
        int cnt = 0;
        while (iter.hasNext()) {
            obj = iter.next();
            cnt++;
            if (cnt == 11086) {
                break;
            }
        }
        Object valueObj = ((Map)obj).get("Value");
        Assertions.assertTrue(valueObj instanceof BigInteger);
        BigInteger val = (BigInteger)valueObj;
        Assertions.assertEquals(18624475000000L, val.longValue());
    }
