### ISSUE TITLE
RdfType property is skipped

### ISSUE THREAD

**Issue by gobertm** [frictionlessdata/tableschema-java#22]
Fields can have "rdfType" properties.
But when the schema is initialised every field is converted to JSONObject and then goes into Field constructor. Which does not care about 'rdfType'

```
public Field(JSONObject field) {
        this.name = field.has("name") ? field.getString("name") : "";
        this.type = field.has("type") ? field.getString("type") : "";
        this.format = field.has("format") ? field.getString("format") : "default";
        this.title = field.has("title") ? field.getString("title") : "";
        this.description = field.has("description") ? field.getString("description") : "";
        this.constraints = field.has("constraints") ? field.getJSONObject("constraints").toMap() : null;
    }
```

**Comment by iSnow** [comment]
Fixed. Field->getRdfType() to read the RDF type of a field.

Test:

    // spec: https://frictionlessdata.io/specs/table-schema/#rich-types
    @Test
    @DisplayName("Test fix for Issue https://github.com/frictionlessdata/tableschema-java/issues/21")
    void testIssue22() {
        String testJson =
                "        {\n" +
                "          \"name\": \"Country\",\n" +
                "          \"type\": \"string\",\n" +
                "          \"rdfType\": \"http://schema.org/Country\"\n" +
                "        }\n";
        Field testField = Field.fromJson(testJson);
        Assertions.assertEquals( "Country", testField.getName());
        Assertions.assertEquals("string", testField.getType());
        Assertions.assertEquals("http://schema.org/Country", testField.getRdfType().toString());
    }
