### ISSUE TITLE
Create a "contributing" section in the readme

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-java#3]
# Overview

It will be great to have a `contributing` section in the readme containing a list of commands required to get started to work on the project. E.g. in Python it contains commands needed to setup virtual environments, install dependencies and run tests.

---

That worked for me:
```bash
# install jabba and maven2
$ cd tableschema-java
$ jabba install 1.8
$ jabba use 1.8
$ mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
$ mvn test -B
```

**Comment by georgeslabreche** [comment]
@pwalsh done!

**Comment by georgeslabreche** [comment]
@roll @pwalsh, this is done.

**Comment by georgeslabreche** [comment]
@roll @pwalsh, should be good now.
