### ISSUE TITLE
Support true/falseValues for boolean type

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-java#4]
# Overview

See http://specs.frictionlessdata.io/table-schema/#boolean

---

Just a note that there was a last minute addition on the specs level. It was easy to implement e.g. for JavaScript - https://github.com/frictionlessdata/tableschema-js/commit/022c1bae8111328a7250b6903ab707fc99cdc671

**Comment by georgeslabreche** [comment]
@roll @pwalsh not sure what I'm missing, please advise. All these test cases pass:
https://github.com/frictionlessdata/tableschema-java/blob/8f8ec8ea2e34eb5b2eec03588d9ca1d682051772/src/test/java/io/frictionlessdata/tableschema/FieldTest.java#L263-L288

**Comment by roll** [comment]
@georgeslabreche 
Sorry if I've missed it from the source/test code. I mean this behaviour:

```python 
field = Field({'name': 'name', 'type': 'type', 'trueValues': ['agreed']})
field.cast_value('true') # ERROR
field.cast_value('agreed') # True
```

**Comment by georgeslabreche** [comment]
OOoooooh!

**Comment by roll** [comment]
Yes I mean customizability - http://specs.frictionlessdata.io/table-schema/#boolean

**Comment by georgeslabreche** [comment]
@roll: I have yet to convince myself on the best approach to include optional _trueValues_ and _falseValues_ parameters for the Field class’ constructors since the type of the Field may not always be boolean. It’s a bit awkward to have _trueValues_ and _falseValues_ constructor parameters for non boolean Field instanciations. Maybe creating a child class called BooleanField will be a better approach?

**Comment by roll** [comment]
@georgeslabreche 
I think it should be the same like e.g. `number` type with a additional properties like `bareNumber`. Is it not possible for the `Field` class constructor to accept `descriptor` argument as we have for Python/JavaScript/etc? It allow to pass things like `format` or `true/falseValues`.

**Comment by iSnow** [comment]
Implemented this on `Table`-level (all BooleanFields for that table will use the new values) and on field-level.

If alternative `true` and `false`-values are set on table-level, no discrimination is made between different columns - ie. setting `true` to `agreed` will disallow `true` for all columns in a given CSV file.  This might not always be desirable, there might be cases where in one column,  `true` should be set to `agreed`, while in another column in the same CSV, `true`  should stay `true`. 

In this case, it is up to the user to set `trueValues` to `['true',  'agreed']`. How does the reference implementation in Python/JS handle this, if at all?

        Map<String, Object> options = new HashMap<>();
        options.put("trueValues", Arrays.asList("agreed", "yep!"));
        options.put("falseValues", Arrays.asList("disagreed", "nope!"));

        Field testField = new BooleanField("name", "default", null, null, null, options);

        // expecting a CastException here
        assertThrows(InvalidCastException.class, () -> {
            testField.castValue("true", false, options);
        });
        // expecting NO CastException here
        testField.castValue("agreed", false, options);
