### ISSUE TITLE
Read and validate a table schema descriptor - not supported remote descriptors

### ISSUE THREAD

**Issue by georgeslabreche** [frictionlessdata/tableschema-java#5]
- [x] Remote schemas support
- [x] strict=False by default.
- [x] strict=False unit testing.

**Comment by georgeslabreche** [comment]
@pwalsh, here's a new constructor which takes in a URL as a parameter:
https://github.com/frictionlessdata/tableschema-java/blob/7168fb305d2c4aba60d969ddbf5f17bc21400bfe/src/main/java/io/frictionlessdata/tableschema/Schema.java#L49-L54

Test cases:
https://github.com/frictionlessdata/tableschema-java/blob/7168fb305d2c4aba60d969ddbf5f17bc21400bfe/src/test/java/io/frictionlessdata/tableschema/SchemaTest.java#L74-L88

**Comment by georgeslabreche** [comment]
I also enforced validation during instanciation of the Schema object. This means that invoking the constructor will now throw a ValidationException if we try to read and load an invalid schema.

**Comment by roll** [comment]
Remote schemas support :+1: 

---

> I also enforced validation during instanciation of the Schema object. This means that invoking the constructor will now throw a ValidationException if we try to read and load an invalid schema.

Lately for Python/JavaScript/Ruby we have established this behaviour (for table schema or data package):

```python
schema = Schema('invalid-descriptor.json')
schema.valid # False
schema.errors # [error1, error2]

schema = Schema('invalid-descriptor.json', strict=Ture) # raise ValidationError
```
It allow still have an ability to work with invalid descriptors. Especially it's important for `datapackage.Package`.

Though not related to this issue.

**Comment by georgeslabreche** [comment]
I kept going back forth on this actually, could never decide on a final behaviour. I shall include the strict flag and make it strict by default then.

**Comment by roll** [comment]
In Py/Js/Rb we have `strict=False` by default. Based on users feedback for many the most important thing is just have an ability to read the data (it's more related to `datapackage.Package` but `tableschema.Schema` just uses the same approach). For now I guess more than half data packages in the world is invalid for specs-v1 validators. So not failing be default seems as a better user experience.
