### ISSUE TITLE
Current tests not passing

### ISSUE THREAD

**Issue by D063520** [frictionlessdata/tableschema-java#57]
When building the current project not all tests are passing .....

[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.022 s <<< FAILURE! - in io.frictionlessdata.tableschema.field.NumberFieldTest
[ERROR] formatNumberField  Time elapsed: 0.014 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<123123[.]123> but was:<123123[,]123>
	at io.frictionlessdata.tableschema.field.NumberFieldTest.formatNumberField(NumberFieldTest.java:27)

**Comment by iSnow** [comment]
What's your locale setting?

**Comment by D063520** [comment]
Sorry, long time ago .... I'm not working on this anymore. If it is compiling now better ; )

**Comment by iSnow** [comment]
Can't reproduce, if someone has more information how to trigger this, we can re-open.
