### ISSUE TITLE
Constraints not working on type Integer

### ISSUE THREAD

**Issue by jonesaaronj** [frictionlessdata/tableschema-java#58]
# Overview

The min, max constraints do not work for integer types.  Pretty sure it's because the IntegerField is casting to a BigInteger, but the Field validator is using Integer.

---

Please preserve this line to notify @iSnow (lead of this repository)

**Comment by jonesaaronj** [comment]
Also, Year is missing from the constraint check entirely

**Comment by jonesaaronj** [comment]
I have a fix for this I could put in a pr for.  Let me know if you are interested.

**Comment by iSnow** [comment]
Hey thanks for the issue, I just noticed after reviewing and merging https://github.com/frictionlessdata/tableschema-java/pull/59 which fixes the exact problem. Could you have a look at it? Would you have done things differently?
