### ISSUE TITLE
Date should support YYYY-[M]M-[D]D

### ISSUE THREAD

**Issue by jonesaaronj** [frictionlessdata/tableschema-java#61]
# Overview

Currently date only supports YYYY-MM-DD but the table schema date type with default format should support YYYY-[M]M-[D]D

---

Please preserve this line to notify @iSnow (lead of this repository)

**Comment by iSnow** [comment]
Not sure that's true. Spec at https://specs.frictionlessdata.io/table-schema/#types-and-formats says "date: This MUST be in ISO8601 format YYYY-MM-DD". Doesn't look like single-digit days/months to me.

IDK, @roll you got an opinion on that?

**Comment by roll** [comment]
Hi @jonesaaronj @iSnow 

According to the specs `format:default` is restricted to `YYYY-MM-DD`. To have it sindle-digit on needs to set custom `format`

**Comment by iSnow** [comment]
There's currently limited support for custom formats in DateField.java (and only in DateField.java) but it won't support single-digit dates and it is a bit ad-hoc to scratch an urgent itch. 

A pull request for a better emulation of the custom date definition from the spec, and which allows single-digit days or months would be very welcome.

**Comment by iSnow** [comment]
Closing as wontfix as it does not conform to the specs.
