### ISSUE TITLE
DateTime is not respecting optional decimal seconds and timezone correctly

### ISSUE THREAD

**Issue by jonesaaronj** [frictionlessdata/tableschema-java#62]
# Overview

The DateTime spec for ISO-8601 allows for the decimal seconds and timezone to be optional

1111-11-11T11:11:11 fails
1111-11-11T11:11:11.555Z passes

---

Please preserve this line to notify @iSnow (lead of this repository)

**Comment by gmeriaux** [comment]
I notice also this issue and if we respect table-schema definition, datetime MUST be in ISO 8601 format of YYYY-MM-DDThh:mm:ssZ in UTC time.
When I look in DatetimeField, I am seeing :
`formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSZ")`
I think you have to replace it by 
`formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss[.SSS]Z")`
milliseconds are optionnal in the ISO 8601 standard
