### ISSUE TITLE
Infer a Table Schema descriptor from a supplied sample of data - there is no stand-alone function

### ISSUE THREAD

**Issue by georgeslabreche** [frictionlessdata/tableschema-java#7]
Infer a Table Schema descriptor from a supplied sample of data - there is no stand-alone function

**Comment by georgeslabreche** [comment]
@roll @pwalsh, type inferral logic is wrapped inside the [TypeInferrer Singleton Class](https://github.com/frictionlessdata/tableschema-java/blob/master/src/main/java/io/frictionlessdata/tableschema/TypeInferrer.java).
A stand-alone inferral method invokation thus looks like this:

`TypeInferrer.getInstance().infer(...)`

Should I still add a convenience method in the Schema class that would simply do the above method invokation?

**Comment by roll** [comment]
@georgeslabreche 
Yes. It's very useful to have it as a part of the public API. In Python and JavaScript `tableschema.infer` function is used very often (sometimes just one function from the whole lib).
