### ISSUE TITLE
Register project at travis-ci.com, please

### ISSUE THREAD

**Issue by iSnow** [frictionlessdata/tableschema-java#70]
# Overview

@roll we used Travis-CI dot ORG  (https://travis-ci.org/frictionlessdata/tableschema-java) as a CI and test pipeline, but that's gone away. Could you please register us at https://www.travis-ci.com/ instead? 

TIA

---

**Comment by roll** [comment]
Hi @iSnow,

We moved Frictionless CI to Github Actions as Travis was about dead. Do you need help with the migration?
