### ISSUE TITLE
datetime type don't respect the specs

### ISSUE THREAD

**Issue by gmeriaux** [frictionlessdata/tableschema-java#74]
This issue is similar to this which was closed for inactivity : https://github.com/frictionlessdata/tableschema-java/issues/62

I notice that in the spec https://specs.frictionlessdata.io/table-schema/#types-and-formats : datetime MUST be in ISO 8601 format of YYYY-MM-DDThh:mm:ssZ in UTC time.
When I look in DatetimeField, I am seeing :
formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
I think you have to replace it by
formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss[.SSS]Z")
milliseconds are optionnal in the ISO 8601 standard

---

Please preserve this line to notify @iSnow (lead of this repository) and @JohannesJander

**Comment by iSnow** [comment]
Thanks for the PR and sorry for the delay, I was busy with life. I merged and released as 0.2.4
