### ISSUE TITLE
Save a table schema descriptor to a file path

### ISSUE THREAD

**Issue by georgeslabreche** [frictionlessdata/tableschema-java#8]
- [x] Schema: Change method name from "write" to "save"
- [x] Schema: Pretty print.
- [x] Table: Change method name from "write" to "save"

**Comment by georgeslabreche** [comment]
This has already been implemented here:
https://github.com/frictionlessdata/tableschema-java/blob/55c364e61944e1a8ad94f2ccb9c6585521a2667d/src/main/java/io/frictionlessdata/tableschema/Schema.java#L173-L177

Test case is here:
https://github.com/frictionlessdata/tableschema-java/blob/55c364e61944e1a8ad94f2ccb9c6585521a2667d/src/test/java/io/frictionlessdata/tableschema/SchemaTest.java#L207-L242

Is it meant to be invokable from somewhere else?

**Comment by georgeslabreche** [comment]
Lack of prettyprint is probably problematic...

**Comment by roll** [comment]
@georgeslabreche 
I've missed it because was searching for `schema.save` according to naming conventions - https://github.com/frictionlessdata/implementations#tableschema. 

Could you rename it to `save` for consistency?

**Comment by georgeslabreche** [comment]
@roll you bet!

**Comment by roll** [comment]
@georgeslabreche 
It's better to preserve readability because a common use case is:
- save descriptor to a file
- update the file manually
- load the file to continue the work
