### ISSUE TITLE
Support true data streaming - it seems for now we read to memory in this.data = this.reader.readAll()

### ISSUE THREAD

**Issue by georgeslabreche** [frictionlessdata/tableschema-java#9]

**Comment by georgeslabreche** [comment]
Might have to implement my own String parser / file line iterator.

**Comment by pwalsh** [comment]
> Might have to implement my own String parser / file line iterator.

Hey @georgeslabreche ! That can't be right, surely? There must be a range of ready-to-go CSV (or, file in general) streaming libraries in Java.

**Comment by roll** [comment]
If there are no streaming csv parsers in Java-world we better backlog this issue and mark as a platform limitation. But hopefully there is some ready-to-go solution.

**Comment by georgeslabreche** [comment]
@pwalsh, When I researched it I had failed to find something that could easily implement the Iterator interface in the way we needed it. Maybe I didn't research hard enough so I will look into it again.

**Comment by georgeslabreche** [comment]
@pwalsh @roll the refactor from issue #18 resolved this. Now using CSVParser in [commons-csv](https://commons.apache.org/proper/commons-csv/) library. Casting from Iterator<CSVRecord> to Iterator<String[]> using the Adaptor Pattern provided by Guava library.

CSVParser needs to be rebuilt from scratch every time we invoke iterator() because _"The parser works record wise. It is not possible to go back, once a record has been parsed from the input stream."_ ([source](https://commons.apache.org/proper/commons-csv/apidocs/index.html?org/apache/commons/csv/CSVParser.html)). Not sure how I feel about that at the moment.

**Comment by pwalsh** [comment]
> CSVParser needs to be rebuilt from scratch every time we invoke iterator() because "[t]he parser works record wise. It is not possible to go back, once a record has been parsed from the input stream" (source). Not sure how I feel about this at the moment.

@georgeslabreche that is the way stream parsing generally works, it is fine.
